id: P9B48B912
initial_creation_type: input
source_metadata:
  title: Kauśikasūtra
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Veda -- Vedāṅga -- Gṛhyasūtra
  data entry: Arlo Griffiths
  contribution to GRETIL: Arlo Griffiths
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:49:50.584512'
last_modified_at: '2022-03-09T14:49:50.584525'
